In [1]:
import numpy as np

In [2]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
a.shape

(2, 4)

In [4]:
a[1,3]

7

In [5]:
a[1,2] = 8

In [6]:
a

array([[0, 1, 2, 3],
       [4, 5, 8, 7]])

In [7]:
a[0]

array([0, 1, 2, 3])

In [8]:
a[1]

array([4, 5, 8, 7])

In [9]:
b = np.array([3,5])
b

array([3, 5])

Generating random numbers

In [10]:
import random

In [12]:
prob = random.random()
print(prob)

0.37028617940813346


In [14]:
number = random.randint(1,6)
print(number)

2


In [16]:
import numpy as np

In [17]:
np.random.randint(1,6,(4,6))

array([[1, 3, 1, 5, 2, 4],
       [5, 2, 2, 3, 5, 4],
       [1, 5, 3, 5, 4, 2],
       [4, 2, 1, 2, 3, 1]])